config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "reviews#index"

  devise_for :users

  resources :media
  resources :follow_requests, except: [:index, :show, :new, :edit]
  resources :products
  resources :reviews

  get "/new" => "reviews#new", as: :new
  get "search", to: "search#index"
  get ":username/followers" => "users#followers", as: :followers
  get ":username/following" => "users#leaders", as: :leaders
  get ":username/pending" => "users#pending", as: :pending

  get ":username" => "users#show", as: :user
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/follow_request.rb
# == Schema Information
#
# Table name: follow_requests
#
#  id           :bigint           not null, primary key
#  status       :string           default("pending")
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  recipient_id :bigint           not null
#  sender_id    :bigint           not null
#
# Indexes
#
#  index_follow_requests_on_recipient_id  (recipient_id)
#  index_follow_requests_on_sender_id     (sender_id)
#
# Foreign Keys
#
#  fk_rails_...  (recipient_id => users.id)
#  fk_rails_...  (sender_id => users.id)
#
class FollowRequest < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :sender, class_name: "User"

  # Enumerating list of values to be stored in columns
  enum status: { pending: "pending", rejected: "rejected", accepted: "accepted" }

  # validations
  validates :recipient_id, uniqueness: { scope: :sender_id, message: "already requested" }

  validate :users_cant_follow_themselves

  def users_cant_follow_themselves
    if sender_id == recipient_id
      errors.add(:sender_id, "can't follow themselves")
    end
  end
end

app/controllers/follow_requests_controller.rb
class FollowRequestsController < ApplicationController
  before_action :set_follow_request, only: %i[ show edit update destroy ]

  # GET /follow_requests or /follow_requests.json
  def index
    @follow_requests = FollowRequest.all
  end

  # GET /follow_requests/1 or /follow_requests/1.json
  def show
  end

  # GET /follow_requests/new
  def new
    @follow_request = FollowRequest.new
  end

  # GET /follow_requests/1/edit
  def edit
  end

  # POST /follow_requests or /follow_requests.json
  def create
    @follow_request = FollowRequest.new(follow_request_params)
    @follow_request.sender = current_user

    respond_to do |format|
      if @follow_request.save
        format.html { redirect_to follow_request_url(@follow_request), notice: "Follow request was successfully created." }
        format.json { render :show, status: :created, location: @follow_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @follow_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /follow_requests/1 or /follow_requests/1.json
  def update
    respond_to do |format|
      if @follow_request.update(follow_request_params)
        format.html { redirect_to follow_request_url(@follow_request), notice: "Follow request was successfully updated." }
        format.json { render :show, status: :ok, location: @follow_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @follow_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follow_requests/1 or /follow_requests/1.json
  def destroy
    @follow_request.destroy

    respond_to do |format|
      format.html { redirect_to follow_requests_url, notice: "Follow request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow_request
      @follow_request = FollowRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def follow_request_params
      params.require(:follow_request).permit(:recipient_id, :sender_id, :status)
    end
end

app/views/follow_requests/_follow_request.html.erb
<div id="<%= dom_id follow_request %>">
  <p>
    <strong>Recipient:</strong>
    <%= follow_request.recipient_id %>
  </p>

  <p>
    <strong>Sender:</strong>
    <%= follow_request.sender_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= follow_request.status %>
  </p>

</div>

app/views/follow_requests/_follow_unfollow.html.erb
<!--Prevents users from sending a follow request to themselves-->
<% unless sender == recipient %>
  <% follow_request = current_user.sent_follow_requests.find_by(recipient: recipient) %>

  <% if follow_request %>
    <% if follow_request.pending? %>
      <%= link_to follow_request,  data: { turbo_method: :delete }, class: "btn btn-outline-secondary" do %>
        Un-request
      <% end %>
    <% elsif follow_request.accepted? %>
      <%= link_to follow_request,  data: { turbo_method: :delete }, class: "btn btn-outline-secondary" do %>
        Un-follow
      <% end %>
    <% end %>
  <% else %>
    <%= render "follow_requests/form", follow_request: recipient.received_follow_requests.build %>
  <% end %>
<% end %>

app/views/follow_requests/_form.html.erb
<%= form_with(model: follow_request) do |form| %>
  <% if follow_request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(follow_request.errors.count, "error") %> prohibited this follow_request from being saved:</h2>

      <ul>
        <% follow_request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :recipient_id %>
  </div>

  <div>
    <%= form.submit "Follow", class: "btn btn-outline-secondary btn-block" %>
  </div>
<% end %>

app/views/follow_requests/edit.html.erb
<h1>Editing follow request</h1>

<%= render "form", follow_request: @follow_request %>

<br>

<div>
  <%= link_to "Show this follow request", @follow_request %> |
  <%= link_to "Back to follow requests", follow_requests_path %>
</div>

app/views/follow_requests/index.html.erb
<h1>Follow requests</h1>

<div id="follow_requests">
  <% @follow_requests.each do |follow_request| %>
    <%= render follow_request %>
    <p>
      <%= link_to "Show this follow request", follow_request %>
    </p>
  <% end %>
</div>

<%= link_to "New follow request", new_follow_request_path %>

app/views/follow_requests/new.html.erb
<h1>New follow request</h1>

<%= render "form", follow_request: @follow_request %>

<br>

<div>
  <%= link_to "Back to follow requests", follow_requests_path %>
</div>

app/views/follow_requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @follow_request %>

<div>
  <%= link_to "Edit this follow request", edit_follow_request_path(@follow_request) %> |
  <%= link_to "Back to follow requests", follow_requests_path %>

  <%= button_to "Destroy this follow request", @follow_request, method: :delete %>
</div>