config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "reviews#index"

  devise_for :users

  resources :media
  resources :follow_requests, except: [:index, :show, :new, :edit]
  resources :products
  resources :reviews

  get "/new" => "reviews#new", as: :new
  get "search", to: "search#index"
  get ":username/followers" => "users#followers", as: :followers
  get ":username/following" => "users#leaders", as: :leaders
  get ":username/pending" => "users#pending", as: :pending

  get ":username" => "users#show", as: :user
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/media.rb
# == Schema Information
#
# Table name: media
#
#  id         :bigint           not null, primary key
#  file       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  owner_id   :bigint           not null
#  review_id  :bigint           not null
#
# Indexes
#
#  index_media_on_owner_id   (owner_id)
#  index_media_on_review_id  (review_id)
#
# Foreign Keys
#
#  fk_rails_...  (owner_id => users.id)
#  fk_rails_...  (review_id => reviews.id)
#
class Media < ApplicationRecord
  belongs_to :review
  belongs_to :owner, class_name: "User"

  include Ransackable
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :set_media, only: %i[ show edit update destroy ]

  # GET /media or /media.json
  def index
    @media = Media.all
  end

  # GET /media/1 or /media/1.json
  def show
  end

  # GET /media/new
  def new
    @media = Media.new
  end

  # GET /media/1/edit
  def edit
  end

  # POST /media or /media.json
  def create
    @media = Media.new(media_params)

    # @media.file params.fetch(:media_file)

    respond_to do |format|
      if @media.save
        format.html { redirect_to media_url(@media), notice: "Media was successfully created." }
        format.json { render :show, status: :created, location: @media }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @media.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media/1 or /media/1.json
  def update
    # @media.file params.fetch(:media_file)
    
    respond_to do |format|
      if @media.update(media_params)
        format.html { redirect_to media_url(@media), notice: "Media was successfully updated." }
        format.json { render :show, status: :ok, location: @media }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @media.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1 or /media/1.json
  def destroy
    @media.destroy

    respond_to do |format|
      format.html { redirect_to media_index_url, notice: "Media was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_media
      @media = Media.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def media_params
      params.require(:media).permit(:file, :review_id)
    end
end

app/views/media/_form.html.erb
<%= form_with(model: media) do |form| %>
  <% if media.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(media.errors.count, "error") %> prohibited this media from being saved:</h2>

      <ul>
        <% media.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :file, style: "display: block" %>
    <%= form.text_field :file %>
  </div>

  <div>
    <%= form.label :review_id, style: "display: block" %>
    <%= form.text_field :review_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/media/_media.html.erb
<div id="<%= dom_id media %>">
  <p>
    <strong>File:</strong>
    <%= media.file %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= media.review_id %>
  </p>

</div>

app/views/media/edit.html.erb
<h1>Editing media</h1>

<%= render "form", media: @media %>

<br>

<div>
  <%= link_to "Show this media", @media %> |
  <%= link_to "Back to media", media_index_path %>
</div>

app/views/media/index.html.erb
<h1>Media</h1>

<div id="media">
  <% @media.each do |media| %>
    <%= render media %>
    <p>
      <%= link_to "Show this media", media %>
    </p>
  <% end %>
</div>

<%= link_to "New media", new_media_path %>

app/views/media/new.html.erb
<h1>New media</h1>

<%= render "form", media: @media %>

<br>

<div>
  <%= link_to "Back to media", media_index_path %>
</div>

app/views/media/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @media %>

<div>
  <%= link_to "Edit this media", edit_media_path(@media) %> |
  <%= link_to "Back to media", media_index_path %>

  <%= button_to "Destroy this media", @media, method: :delete %>
</div>