config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "reviews#index"

  devise_for :users

  resources :media
  resources :follow_requests, except: [:index, :show, :new, :edit]
  resources :products
  resources :reviews

  get "/new" => "reviews#new", as: :new
  get "search", to: "search#index"
  get ":username/followers" => "users#followers", as: :followers
  get ":username/following" => "users#leaders", as: :leaders
  get ":username/pending" => "users#pending", as: :pending

  get ":username" => "users#show", as: :user
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]
  before_action :ensure_current_user_is_owner, only: [:destroy, :update, :edit]
  before_action :ensure_user_is_authorized, only: [:show]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
    authorize @review
  end

  # GET /reviews/new
  def new
    @review = Review.new
    @review.product_id = params[:product_id] if params[:product_id]
    @review.product_name = params[:product_name] if params[:product_name]
    @review.published = true
  end

  # GET /reviews/1/edit
  def edit
    @review.product_name = params[:product_name] if params[:product_name]
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)
    # @review.image = params

    @review.owner_id = current_user.id
    @review.published = true

    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    if current_user == @review.owner
      @review.destroy

      respond_to do |format|
        format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_back(fallback_location: root_url, notice: "Nice try, but that is not your review.")
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:owner_id, :product_id, :rating, :would_repurchase, :body, :visibility, :published, :image)
    end

    # seems like this could be handled in a review policy

  # Authorization
    def ensure_current_user_is_owner
      if current_user != @review.owner
        redirect_back fallback_location: root_url, alert: "You're not authorized for that."
      end
    end

# Not needed when 'include Pundit' is in the app controller
    def ensure_user_is_authorized
      if !ReviewPolicy.new(current_user, @review).show?
        raise Pundit::NotAuthorizedError, "not allowed"
      end
    end

    # REMOVE COMMENTED OUT CODE
    # def ensure_user_is_authorized
    #   authorize @review
    # rescue Pundit::NotAuthorizedError
    #   flash[:alert] = "You are not authorized to view this review."
    #   redirect_to root_url
    # end
end

app/views/reviews/_form.html.erb
<%= form_with(model: review) do |form| %>
  <% if review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <hr>

  <form>
    <fieldset>
      <div class="form-group">
        <div class="col-sm-10">
          <%= form.hidden_field :product_id, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :product_name, class: 'col-sm-2 col-form-label mt-4' %>
        <div class="col-sm-10">
          <%= form.text_field :product_name, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :rating, class: 'form-label mt-4' %>
        <%= form.select :rating, [[ 'Select one', nil ]] + (1..10).map { |i| [i, i] }, { class: 'form-select' } %>
      </div>

      <div class="form-group">
        <%= form.label :would_repurchase, class: 'form-label mt-4' %>
        <%= form.select :would_repurchase, [['Select one', nil], ['Yes', "yes"], ['No', "no"], ['Maybe', "maybe"]], { class: 'form-select' } %>
      </div>

      <div class="form-group">
        <%= form.label :body, class: 'form-label mt-4' %>
        <%= form.text_area :body, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :visibility, class: 'form-label mt-4' %>
        <%= form.select :visibility, [['Select one', nil], ['Only me', "only_me"], ['Followers', "followers_only"], ['Everyone', "everyone"]], { class: 'form-select' } %>
      </div>

      <div class="form-group">
        <%= form.label :image, class: 'form-label mt-4' %>
        <%= form.file_field :image, class: 'form-control' %>
      </div>

      <button type="submit" class="btn btn-primary mt-4">Submit</button>
    </fieldset>
  </form>
  
  <hr>
<% end %>

app/views/reviews/_review.html.erb
<div class="card mb-3" style="max-width: 25rem;">
  <h3 class="card-header"><%= review.product.name %></h3>
  <div class="card-body">
    <h5 class="card-title">Rating: <%= review.rating %>/10</h5>
    <h6 class="card-subtitle mb-2 text-muted">Would Repurchase? <%= review.would_repurchase.capitalize %></h6>

  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Notes: <%= review.body %></li>
    <li class="list-group-item">Media:
      <div>
        <!-- Cloudinary Media -->
        <img src="<%= review.image.url %>" class="img-responsive" width="350" alt="Media Image">
      </div>
    </li>
  </ul>
  <div class="card-body">
    <%= link_to "#{review.owner.username}", user_path(username: review.owner.username), class: "card-link" %>
    <%= link_to "Show this review", review, class: "card-link" %>
  </div>
  <div class="card-footer text-muted">
    <%= Time.now.strftime("%d %B, %Y") %>
  </div>
</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Show this review", @review %> |
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<%# Broken on mobile view %>
<div id="reviews" class="center_review">
  <% @reviews.each do |review| %>
    <%# Would be better to have this logic in a ReviewPolicy eg policy(review).index? or use a pundit scope to only return reviews that can be shown to this user %>
    <!--Only show if review is published, user is not review' owner, or if the review is not set to only me and user is following the review's owner-->
    <% if (review.owner != current_user) && (review.visibility != 'only_me' && review.owner.followers.include?(current_user)) %>
      <% if review.published? %>
        <%= render review, user: current_user %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/show.html.erb
<%= link_to "Back to reviews", reviews_path %>

<%= render @review, user: current_user %>

<div>
  <% if current_user == @review.owner %>
    <%= link_to "Edit this review", edit_review_path(@review, product_name: @review.product.name) %>
    <%= button_to "Destroy this review", @review, method: :delete %>
  <% end %>
</div>